export const UPDATE_STATUS = 'UPDATE_STATUS';

export const SET_CURRENT_DEFAULT_PROFILE = 'SET_CURRENT_DEFAULT_PROFILE';
export const RESET_REFRESH = 'RESET_REFRESH';
export const SET_INSTALLATION = 'SET_INSTALLATION';

export const SET_SINGLE_USER = 'SET_SINGLE_USER';
export const SET_SEARCHED_USERS = 'SET_SEARCHED_USERS';
export const SET_USER_FILTER = 'SET_USER_FILTER';
export const SET_USERS_TAB = 'SET_USERS_TAB';
export const SET_USERS = 'SET_USERS';
export const SET_PER_USER = 'SET_PER_USER';
export const SET_DEFAULT_PROFILES = 'SET_DEFAULT_PROFILES';
export const SET_CURRENT_USER_PROFILE = 'SET_CURRENT_USER_PROFILE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGES = 'DELETE_FLASH_MESSAGES';

export const SET_CUSTOM_MODAL_TAB = 'SET_CUSTOM_MODAL_TAB';

export const SET_VEHICLES = 'SET_VEHICLES';
export const SET_ACTIVE_VEHICLE = 'SET_ACTIVE_VEHICLE';
export const SET_ALL_VEHICLES = 'SET_ALL_VEHICLES';
export const SET_FOUND_VEHICLE = 'SET_FOUND_VEHICLE';
export const SET_SEARCHED_VEHICLES = 'SET_SEARCHED_VEHICLES';

export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const CLOSE_NAV = 'CLOSE_NAV';
export const TOGGLE_NAV = 'TOGGLE_NAV';
